/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class APP */

#ifndef _Included_APP
#define _Included_APP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     APP
 * Method:    calcBill
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_APP_calcBill
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
